spring.application.name=barber-booking

spring.datasource.url=jdbc:mysql://localhost:3306/barber_shop
spring.datasource.username=root
spring.datasource.password=Pass@1219

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true